---
- name: limit example play
  hosts: all
  gather_facts: false

  tasks:
    - name: tell us which hosts are on
      debug:
        var: inventory_hostname

    - name: grab variables from webserver1
      debug:
        var: hostvars['webserver1.ubuntu.com']['ansible_ssh_port']
