# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web1" do |web1|
    web1.vm.box                      = "hashicorp-vagrant/ubuntu-16.04"
    web1.ssh.username                = "vagrant"
    web1.ssh.password                = "vagrant"
    web1.ssh.insert_key              = false
    web1.ssh.forward_agent           = true
    web1.vm.box_check_update         = false
    web1.vm.hostname                 = "web1.ubuntu.com"
    web1.vm.network                  "private_network", ip: "192.168.100.3"
    web1.vm.synced_folder            "web1", "/vagrant"
    web1.vm.provision                :shell, path: "web1/bootstrap.sh"
  end
  config.vm.define "ans" do |ans|
    ans.vm.box                      = "hashicorp-vagrant/ubuntu-16.04"
    ans.ssh.username                = "vagrant"
    ans.ssh.password                = "vagrant"
    ans.ssh.insert_key              = false
    ans.ssh.forward_agent           = true
    ans.vm.box_check_update         = false
    ans.vm.hostname                 = "ans.ubuntu.com"
    ans.vm.network                  "private_network", ip: "192.168.100.2"
    ans.vm.provision                :shell, path: "ans/bootstrap.sh"
  end
end


