---
- name: Configure webserver with nginx
  hosts: webservers
  become: yes
  tasks:
    - name: install epel-release
      yum: name=epel-release
    - name: install nginx
      yum: name=nginx
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/
    - name: copy index.html
      template: >
        src=templates/index.html.j2 
        dest=/usr/share/nginx/html/index.html
        mode=0644
    - name: restart nginx
      service: name=nginx state=restarted


