---
- name: Configure webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Install nginx
      yum: name=nginx
    - name: Install config file
      template: src=files/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: restart nginx
    - name: notify nginx
      service: name=nginx state=restarted

