---
- hosts: localhost
  gather_facts: false

  vars:
  - a_var: derp

  pre_tasks:
  - name: pre_task
    debug: msg="a pre task"
    changed_when: true
    notify: say hi

  roles:
  - role: simple
    derp: newval

  tasks:
  - name: task
    debug: msg="a task"
    changed_when: true
    notify: say hi
  
  post_tasks:
  - name: post_task
    debug: msg="a post task"
    changed_when: true
    notify: say hi
