---
- name: demo the template
  hosts: localhost
  gather_facts: false

  vars:
    api:
      v2: false

  tasks:
    - name: pause the render
      debug:
        msg:  "API = cinder{{ 'v2' if api.v2 else '' }}"

